apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: default
data:
  index.html: |
    <html>
    <head><title>ArgoCD GitOps Demo</title></head>
    <body>
      <h1>Hello from GitOps</h1>
      <p>This page was deployed via ArgoCD!</p>
    </body>
    </html>

